export const allItems = [
    { id: 1, label: "Solar Products & Services" },
    { id: 2, label: "Solar Operation & Maintenance" },
    { id: 3, label: "Site capture" },
    { id: 4, label: "Remote Operations" },
    { id: 5, label: "Performance Engineering" },
    { id: 6, label: "Preventive and corrective maintenance" },
    { id: 7, label: "Drone Inspection" },
    { id: 8, label: "Vegetation Management" },
    { id: 9, label: "Technical Support" },
    { id: 10, label: "Comertial Products" },
    { id: 11, label: "Solar Panels" },
    { id: 12, label: "Monocrystalline Solar Panels" },
    { id: 13, label: "Polycrystalline Solar Panels" },
    { id: 14, label: "Thin Film Solar Panels" },
    { id: 15, label: "PERC Solar Panels" },
    { id: 16, label: "Bifasics Solar Panels" },
    { id: 17, label: "Building-Integrated Solar Panels" },
    { id: 18, label: "Concentrated Solar Panels" },
    { id: 19, label: "Hybrid Solar Panels" },
    { id: 20, label: "Solar Racking Supply" },
    { id: 21, label: "Roof Mount Racking" },
    { id: 22, label: "Grood Mount Racking" },
    { id: 23, label: "Poly Mount Racking" },
    { id: 24, label: "Hybrid Mount Racking" },
    { id: 25, label: "Floating Solar Racking" },
    { id: 26, label: "Solar Carport Racking" },
    { id: 27, label: "Solar Roof Tiles" },
    { id: 28, label: "Solar Tracking" },
    { id: 29, label: "Solar Roof Mount" },
    { id: 30, label: "Energy Solutions" },
    { id: 31, label: "Solar Energy Batteries" },
    { id: 32, label: "Lithium-lon (li-ion) Batteries" },
    { id: 33, label: "Microinverters" },
    { id: 34, label: "Lead Acid Batteries" },
    { id: 35, label: "SaultWater Batteries" },
    { id: 36, label: "Flow Batteries" },
    { id: 37, label: "Nickel-Cadmium (NiCd) Batteries" },
    { id: 38, label: "Lithium Iron Phosphate (LiFePO4) Batteries" },
    { id: 39, label: "Zinc-Air Batteries" },
    { id: 40, label: "Solar Energy Inverters" },
    { id: 41, label: "String Inverters" },
    { id: 42, label: "Power Optimizers" },
    { id: 43, label: "Central Inverters" },
    { id: 44, label: "Hybrid Inverters" },
    { id: 45, label: "Grid-Tie Inverters" },
    { id: 46, label: "Three-Phase Inverters" },
    { id: 47, label: "DC-AC Hybrid Inverters" },
    { id: 48, label: "Tools Equipment & Safety" },
    { id: 49, label: "Solar Energy Tools" },
    { id: 50, label: "Solar Panel Installation Tools" },
    { id: 51, label: "Electrical Tools" },
    { id: 52, label: "Solar Racking and Mounting Tools" },
    { id: 53, label: "Solar Monitoring Tools" },
    { id: 54, label: "Miscellaneous Tools" },
    { id: 55, label: "Safety" },
    { id: 56, label: "Personal Protective Equipment (PPE)" },
    { id: 57, label: "Fall Protection Equipment" },
    { id: 58, label: "Electrical Safety Equipment" },
    { id: 59, label: "Fire Safety Equipment" },
    { id: 60, label: "First Aid Equipment" },
    { id: 61, label: "Worksite Safety Measures" },
    { id: 62, label: "Hardscapes & Outdoor Living" },
    { id: 63, label: "Pavers" },
    { id: 64, label: "Concreate Pavers" },
    { id: 65, label: "Brick Pavers" },
    { id: 66, label: "Retaining Walls" },
    { id: 67, label: "Block Retaining Walls" },
    { id: 68, label: "Natural Stone Walls" },
    { id: 69, label: "Outdoor Living" },
    { id: 70, label: "Fire Pits" },
    { id: 71, label: "Outdoor Kitchens" },  
];
export const middleList = [
  {
    _id: 2221,
    title: "Get to Know Us",
    listItem: [
      {
        _id: "001",
        listData: [
          "Careers",
          "Blog",
          "About Amazon",
          "Investor Relations",
          "Amazon Devices",
          "Amazon Science",
        ],
      },
    ],
  },
  {
    _id: 2222,
    title: "Make Money with Us",
    listItem: [
      {
        _id: "002",
        listData: [
          "Sell products on Amazon",
          "Sell on Amazon Business",
          "Sell apps on Amazon",
          "Become an Affiliate",
          "Advertise Your Products",
          "Sell Product with Us",
          "Host an Amazon Hub",
          "See More Make Money with Us",
        ],
      },
    ],
  },
  {
    _id: 2223,
    title: "Amazon Payment Products",
    listItem: [
      {
        _id: "003",
        listData: [
          "Amazon Business Card",
          "Shop with Points",
          "Reload Your Balance",
          "Amazon Currency Converter",
        ],
      },
    ],
  },
  {
    _id: 2224,
    title: "Let Us Help You",
    listItem: [
      {
        _id: "004",
        listData: [
          "Amazon and COVID-19",
          "Your Account",
          "Your Orders",
          "Shipping Rates & Policies",
          "Returns & Replacements",
          "Manage Your Content and Devices",
          "Amazon Assistant",
          "FAQ & Help",
        ],
      },
    ],
  },
];
export const footerBottomItem = [
  {
    _id: 1001,
    title: "Amazon Music",
    des: "Stream millions of songs",
  },
  {
    _id: 1002,
    title: "	Amazon Advertising",
    des: "Find, attract, and engage customers",
  },
  {
    _id: 1003,
    title: "Amazon Drive",
    des: "Cloud storage from Amazon",
  },
  {
    _id: 1004,
    title: "6pm",
    des: "Score deals on fashion brands",
  },
  {
    _id: 1005,
    title: "AbeBooks",
    des: "Books, art & collectibles",
  },
  {
    _id: 1006,
    title: "ACX",
    des: "Audiobook Publishing Made Easy",
  },
  {
    _id: 1007,
    title: "Sell on Amazon",
    des: "Start a Selling Account",
  },
  {
    _id: 1008,
    title: "Amazon Business",
    des: "Everything For Your Business",
  },
  {
    _id: 1009,
    title: "AmazonGlobal",
    des: "Ship Orders Internationally",
  },
  {
    _id: 1010,
    title: "Home Services",
    des: "Experienced Pros appiness Guarantee",
  },
  {
    _id: 1011,
    title: "Amazon Ignite",
    des: "Sell your original Digital Educational Resources",
  },
  {
    _id: 1012,
    title: "Amazon Web Services",
    des: "Scalable Cloud Computing Services",
  },
  {
    _id: 1013,
    title: "Audible",
    des: "Listen to Books & Original Audio Performances",
  },
  {
    _id: 1014,
    title: "Book Depository",
    des: "Books With Free Delivery Worldwide",
  },
  {
    _id: 1015,
    title: "Box Office Mojo",
    des: "Find Movie Box Office Data",
  },
  {
    _id: 1016,
    title: "ComiXology",
    des: "Thousands of Digital Comics",
  },
  {
    _id: 1017,
    title: "DPReview",
    des: "Digital Photography",
  },
  {
    _id: 1018,
    title: "Fabric",
    des: "Sewing, Quilting & Knitting",
  },
  {
    _id: 1019,
    title: "Goodreads",
    des: "Book reviews & recommendations",
  },
  {
    _id: 1020,
    title: "IMDb",
    des: "Movies, TV & Celebrities",
  },
  {
    _id: 1021,
    title: "	IMDbPro",
    des: "Get Info Entertainment Professionals Need",
  },
  {
    _id: 1022,
    title: "Kindle Direct Publishing",
    des: "Indie Digital & Print Publishing Made Easy",
  },
  {
    _id: 1023,
    title: "Prime Video Direct",
    des: "Video Distribution Made Easy",
  },
  {
    _id: 1024,
    title: "Shopbop",
    des: "Designer Fashion Brands",
  },
  {
    _id: 1025,
    title: "Woot!",
    des: "Deals and Shenanigans",
  },
  {
    _id: 1026,
    title: "Zappos",
    des: "Shoes & Clothing",
  },
  {
    _id: 1027,
    title: "Ring",
    des: "Smart Home Security Systems",
  },
  {
    _id: 1028,
    title: "eero WiFi",
    des: "Stream 4K Video in Every Room",
  },
  {
    _id: 1029,
    title: "Blink",
    des: "Smart Security for Every Home",
  },
  {
    _id: 1030,
    title: "Neighbors App",
    des: "Real-Time Crime & Safety Alerts",
  },
  {
    _id: 1031,
    title: "Amazon Subscription Boxes",
    des: "Top subscription boxes - right to your doo",
  },
  {
    _id: 1032,
    title: "PillPack",
    des: "Pharmacy Simplified",
  },
];
